### ISSUE TITLE
[Fluster] MR1_BT_A, MR2_TANDBERG_E, MR6_BT_B, MR7_BT_B, MR8_BT_B, MR9_BT_B failing on Intel only

### ISSUE THREAD

**Issue by Gnurou** [chromeos/cros-codecs#15]
Strange case of tests failing to pass only on Intel platforms:

* `MR1_BT_A`,  `MR2_TANDBERG_E`, `MR8_BT_B` show macroblock corruption after a few frames.
* `MR6_BT_B`, `MR7_BT_B`, `MR9_BT_B` don't have visible corruption, but rather very small alterations that require a hex editor to see.

Note that on  `MR2_TANDBERG_E`, `MR6_BT_B`, `MR7_BT_B` and `MR8_BT_B` the `FFmpeg-H.264-VAAPI` decoder seems to fall back to software decoding for some reason. But other files seem to be successfully decoded by FFmpeg on Intel (and all pass with `ccdec` on AMD).

**Comment by dwlsalmeida** [comment]
So for `MR1_BT_A`, there's a difference in the ref_pic_list0:

GStreamer-VA:

```
.500653][ctx 0x10000001]	RefPicList0 =
[14537.500653][ctx 0x10000001]00000002-00000002-0x0000000f-00000002-0x00000008
[14537.500654][ctx 0x10000001]00000001-00000001-0x0000000e-00000001-0x00000008
[14537.500654][ctx 0x10000001]00000001-00000001-0x0000000e-00000001-0x00000008
```

cros-codecs:
```
[14521.854094][ctx 0x10000000]	RefPicList0 =
[14521.854094][ctx 0x10000000]00000002-00000002-0x00000002-00000002-0x00000008
[14521.854095][ctx 0x10000000]00000001-00000001-0x00000001-00000001-0x00000008
[14521.854095][ctx 0x10000000]00000000-00000000-0x00000000-00000000-0x00000008
```

I am going to go on a hunch and say that `MR2_TANDBERG_E` and `MR8_BT_B` fail for the same reason.

The surprising part: this also passes for me on my AMD box. I have 0 idea how, will investigate further tomorrow

**Comment by dwlsalmeida** [comment]
@Gnurou can we skip anything that fails only on a specific driver? The data sent to both is the same. If one implementation fails, that's on the implementation.

I just checked here and both `MR8_BT_B` and `MR9_BT_B` pass on my AMD machine.

**Comment by Gnurou** [comment]
Sorry, forgot to reply to this one. I could confirm that `MR8_BT_B` and `MR9_BT_B` are both passing on AMD (interestingly, `MR8_BT_B` fails on the same machine with `GStreamer-H.264-VAAPI-Gst1.0`). So let's close this for now as this seems to be an Intel-specific issue.
