### ISSUE TITLE
JVT-FR-EXT test suite has lots of failures

### ISSUE THREAD

**Issue by Gnurou** [chromeos/cros-codecs#26]
`JVT-FR-EXT` is failing quite badly comparatively to `JVT-AVC_V1`.

`ccdec` has 12/69 tests passing.

`GStreamer-H.264-VAAPI-Gst1.0` has 43/69 tests passing.

Attached the first frame from one of the first failing tests (`brcm_freh3`), it seems like key frames are not decoded correctly.

![brcm_freh3_ccdec](https://github.com/chromeos/cros-codecs/assets/148255/24b739c5-9e0c-41b3-8310-706db80b8242)

**Comment by dwlsalmeida** [comment]
Closing as there's no more progress that can be done for now on our end
