### ISSUE TITLE
h264: a slice may refer to a previous SPS but we do not renegotiate

### ISSUE THREAD

**Issue by dwlsalmeida** [chromeos/cros-codecs#35]
This is not tested by any of our h264 test suites, but a slice may very well refer to a previous SPS than the latest one parsed. If we identify this, we should [renegotiate if needed](https://github.com/chromeos/cros-codecs/blob/main/src/decoder/stateless/h264.rs#L291) using the SPS referred to by the slice, instead of peeking for a new one.

We should also:

a) refrain from processing any more input in `decode_access_unit()` if this is detected
b) return the actual bitstream offset, so that the client can reissue the call with the data only from that point on, i.e.: `decoder.decode(&bitstream[current_offset..])`.

For b), we can query the current offset from [the cursor](https://github.com/chromeos/cros-codecs/blob/main/src/decoder/stateless/h264.rs#L2129), and return that in `DecodingState::AwaitingFormat`. together with the actual SPS referred to by the slice.

**Comment by Gnurou** [comment]
I think this has been fixed by https://github.com/chromeos/cros-codecs/pull/45/commits/239c37c3e4438642c36572cddf7767c4d3eac8e7, can we close?

**Comment by dwlsalmeida** [comment]
Yes, that solves it
