### ISSUE TITLE
We should rename all occurrences of the term "Surface" in non-vaapi code

### ISSUE THREAD

**Issue by dwlsalmeida** [chromeos/cros-codecs#36]
This will be very confusing when/if other backends (like v4l2 backends) come along.

For consistency, we should rename this at the decoder level.

My suggestion is to use the term `resource`, meaning some backend-specific buffer or data structure consumed during decode, like `VASurface`, `V4L2Request`, `V4L2Buffer`, `VkMemory` and etc.

**Comment by Gnurou** [comment]
That's probably a good idea, agreed. We should probably also define the terminology we use in the online doc.

"Resource" always sounds to me like we are mining ore or something though. How about just "Frame"? A frame is made of memory buffers, has planes, and a given format.

**Comment by dwlsalmeida** [comment]
`Frame` is fine then

**Comment by Gnurou** [comment]
Fixed by 06ac7b3c9e5fe3bd06a4f42a8a9ea31a0b808019.
