### ISSUE TITLE
av1: max for secondary strength looks incorrect

### ISSUE THREAD

**Issue by Gnurou** [chromeos/cros-codecs#58]
As per Nicolas Dufresne:

> the max for secondary strength is incorrect here, https://github.com/chromeos/croscodecs/blob/main/src/codec/av1/parser.rs#L921
> Secondary strength is 2 bit in the bitstream
> as you apply the +1, its not even a range, is 0 1 2 4

Let's check and fix if needed.

**Comment by dwlsalmeida** [comment]
This is fine, the array is a bit larger than it should be, right @ndufresne ?

**Comment by ndufresne** [comment]
My bad, its fine indeed, you can close.
