### ISSUE TITLE
Releasing a new version with encoders

### ISSUE THREAD

**Issue by dmb-ish** [chromeos/cros-codecs#90]
First, thanks a lot for your work on this crate!

I'm able to successfully use the stateless VA-API H.264 encoder (and decoder). However as it's not currently included in the version released on crates.io, I have to add `cros-codecs` as a git dependency, which prevents me from publishing my own crate on crates.io (as [crates.io requires that all dependencies be published on crates.io as well](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-other-registries)).

Would you consider publishing a new release on crates.io that would include the (stateless) encoders?

**Comment by Gnurou** [comment]
Hi! Thanks for your interest in this project!

@bgrzesik will publish a new release soon.

**Comment by bgrzesik** [comment]
The version [v0.0.5](https://github.com/chromeos/cros-codecs/tree/v0.0.5) have been just released. Enjoy!
